environment:
  host: 0.0.0.0
  port: 8000
  debug: true
  use_cpu: true
  save_image_directory: images/

model:
  model_path: models/ver1.pkl
  feature_extractor_model: resnet50
  batch_size: 2048
  target_size: 224
  threshold:
