dash_environment:
  host: 0.0.0.0
  port: 8000
  debug: false
  use_cpu: true
  save_image_directory: images/
  log_filepath: logs/dash_app.log
  shell_family_reset_api: http://task-app:7000/shell_family_reset

task_app_environment:
  host: 0.0.0.0
  port: 7000
  debug: false
  use_cpu: true
  seconds_interval: 10
  coalesce: false
  max_instances: 3
  log_filepath: logs/task_app.log

database:
  username: mitb
  password: mitb-il-2021
  host: postgresql
  port: 5432
  database_name: incremental_learner

model:
  shell_family_id: learner_1
  feature_extractor_model: resnet50
  batch_size: 1024
  target_size: 224
  threshold:
